### ISSUE TITLE
Villager in Trade Recipe GUI is missing textures

### ISSUE THREAD

**Issue by darthvader45** [way2muchnoise/JustEnoughResources#493]
### Steps to Reproduce the Bug

Hit the 'view recipes' keybind while hovering over anything that can be traded to a villager.
Click the 'Villager Trading' icon (the three emeralds)
See that the villager texture in the entity window is missing.
Expected Behavior
The villager displayed should have their respective texture.

### Actual Behavior

The villager is missing a texture.

### Mod Pack URL (Optional)

No response

### Mod Pack Version (Optional)

No response

### Extra Notes (Optional)

No response

### latest.log:
https://gist.github.com/darthvader45/9715e807dc07808d706431dfdb9819ab

**Comment by way2muchnoise** [comment]
What is the version of JER you are using? I thought I fixed this in ff94130ed22439c5137c7d61f80209757a6557fd (version 1.5.1 of JER).

**Comment by darthvader45** [comment]
Weirdly enough, 1.4.x.x.  I'll try updating, though that was the latest one for 1.20.1 that I could find.

**Comment by deerflow** [comment]
I'm on latest version on both JEI and JER and I've got the problem too.
I can hover the empty case and still get the item name btw.
![2024-08-12_17 28 17](https://github.com/user-attachments/assets/01f1a68a-81a9-4e51-8d77-973ef9edb426)
